DROP TABLE IF EXISTS patrimoine;
CREATE TABLE patrimoine (
	id integer(10),
	id_no varchar(10),
	rev_bis varchar(30),
	name_en varchar(255),
	name_fr varchar(255),
	short_description_en text,
	short_description_fr text,
	justification_en text,
	justification_fr text,
	date_inscribed varchar(20),
	secondary_dates varchar(20),
	danger varchar(50),
	date_end varchar(50),
	danger_list varchar(50),
	longitude varchar(20),
	latitude varchar(20),
	area_hectares varchar(20),
	C1 int(3),
	C2 int(3),
	C3 int(3),
	C4 int(3),
	C5 int(3),
	C6 int(3),
	N7 int(3),
	N8 int(3),
	N9 int(3),
	N10 int(3),
	criteria_txt varchar(50),
	category varchar(50),
	category_short varchar(5),
	states_name_en varchar(255),
	states_name_fr varchar(255),
	continent_name_en varchar(255),
	continent_name_fr varchar(255),
	iso_code varchar(50),
	udnp_code varchar(50),
	transboundary int(3),
	coordonnees varchar(255),
	multiple int(3),
	id_multiple varchar(8),
	name_multiple varchar(255),
	primary key(id),
	key(id_no),
    key(coordonnees),
    key(name_fr),
    key(name_en),
    key(multiple),
    key(name_multiple)
) CHARSET=utf8;

